# Generated by Django 6.1.1 on 2026-09-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor_str',
        ),
    ]
